import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {BedDouble,LayoutDashboard,Braces,ArrowLeftRight,Download,RefreshCw,Search,ChevronRight,ArrowUpRight,Activity,ShieldCheck,AlertCircle,Check,Menu} from 'lucide-react';
import {BASE,DATASET,SOURCE,TARGET} from './config.js';
import {mappings,conceptMap,normalize,filterRows,counts,makeCsv} from './domain.js';
import {loadBeds} from './api.js';
import './style.css';
const tabs=[['dashboard','Vue d’ensemble',LayoutDashboard],['fhir','Ressources FHIR',Braces],['mapping','Correspondances',ArrowLeftRight],['csv','Export CSV',Download]];
const date=(v)=>v?new Date(v).toLocaleString('fr-FR',{dateStyle:'short',timeStyle:'medium'}):'Non renseigné';
function Badge({state,label}){return <span className={`badge ${state}`}><i/>{label}</span>;}
function App(){
 const [tab,setTab]=useState('dashboard'),[resources,setResources]=useState([]),[logs,setLogs]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[complete,setComplete]=useState(false),[loaded,setLoaded]=useState(''),[pages,setPages]=useState(0),[query,setQuery]=useState(''),[state,setState]=useState(''),[selected,setSelected]=useState(''),[dataset,setDataset]=useState(DATASET),[draft,setDraft]=useState(DATASET),[settings,setSettings]=useState(false),[copied,setCopied]=useState(false);
 const abort=useRef(null);const {rows,excluded}=normalize(resources);const visible=filterRows(rows,query,state);const stats=counts(visible);const current=rows.find(r=>r.id===selected)||rows[0];const csv=makeCsv(visible,BASE,loaded);
 async function refresh(value=dataset){abort.current?.abort();const controller=new AbortController();abort.current=controller;setLoading(true);setError('');setComplete(false);setPages(0);const start=new Date().toISOString();try{const result=await loadBeds(value,{signal:controller.signal,log:entry=>{if(!controller.signal.aborted)setLogs(old=>[entry,...old].slice(0,100));},onProgress:(data,n)=>{if(!controller.signal.aborted){setResources([...data]);setPages(n);}}});if(controller.signal.aborted)return;setResources(result.resources);setLoaded(start);setComplete(true);}catch(e){if(!controller.signal.aborted)setError(e.message);}finally{if(!controller.signal.aborted)setLoading(false);}}
 useEffect(()=>{refresh();return()=>abort.current?.abort();},[]);
 function download(){if(!complete||loading||error)return;const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`bedview-lits-${new Date().toISOString().replaceAll(':','-')}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
 const title=tabs.find(t=>t[0]===tab)[1];
 return <div className="shell"><aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setTab('dashboard');}}><span className="brand-icon"><BedDouble size={25}/></span>bedview<span className="brand-dot">.</span></a><div className="workspace"><span className="workspace-icon">U</span><div><strong>Unité de démonstration</strong><small>Gestion des lits</small></div></div><p className="nav-label">ESPACE DE TRAVAIL</p><nav>{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={tab===id?'active':''}><Icon size={19}/>{label}{tab===id&&<ChevronRight size={15}/>}</button>)}</nav><div className="sidebar-bottom"><div className="server-card"><span className="dot"/> HAPI FHIR R4<small>Serveur public de test</small></div><div className="profile"><span>RS</span><div><strong>Responsable de service</strong><small>Espace de démonstration</small></div></div></div></aside>
 <div className="main"><header className="topbar"><span>Unité de démonstration <ChevronRight size={14}/> <strong>{title}</strong></span><span className="demo-pill"><ShieldCheck size={14}/> Données fictives</span></header><main><div className="heading"><div><div className="eyebrow">SUIVI DES LITS</div><h1>{title}</h1><p>{tab==='dashboard'?'Une vision claire des états déclarés de votre unité.':tab==='fhir'?'Consultez les données reçues et la trace de chaque échange.':tab==='mapping'?'Du code FHIR au vocabulaire métier, sans perdre le sens.':'Préparez un export des lits de votre sélection.'}</p></div><button className="button" disabled={loading} onClick={()=>refresh()}><RefreshCw size={16} className={loading?'spin':''}/>{loading?'Chargement…':'Actualiser'}</button></div>
 <div className="statusbar"><span><i className={`dot ${error?'red':''}`}/>{loading?`Lecture du serveur · ${pages} page(s) reçue(s)`:error?'Actualisation interrompue':complete?'Connexion HAPI établie':'En attente de connexion'}</span><span>{loaded?`Dernière récupération : ${date(loaded)}`:'Connexion réelle · FHIR 4.0.1'}<button className="text-button" onClick={()=>setSettings(!settings)}>Périmètre</button></span></div>
 {settings&&<form className="settings" onSubmit={e=>{e.preventDefault();if(!draft.trim())return;setDataset(draft.trim());setResources([]);setQuery('');setState('');refresh(draft.trim());}}><label>Identifiant du jeu HAPI<input value={draft} onChange={e=>setDraft(e.target.value)} required/></label><button className="button">Charger ce périmètre</button><small>Recherche par tag urn:bedview:dataset. Les données sont toujours relues sur HAPI.</small></form>}
 {error&&<div className="error" role="alert"><AlertCircle size={20}/><div><strong>Impossible de terminer le chargement</strong><p>{error} Les données visibles peuvent être partielles ou non actualisées. L’export est désactivé.</p></div><button onClick={()=>refresh()}>Réessayer</button></div>}
 {tab==='dashboard'&&<><div className="metrics"><article className="metric featured"><span>Lits affichés <BedDouble size={20}/></span><strong>{visible.length.toString().padStart(2,'0')}</strong><small>sur {rows.length} lits du périmètre</small><div className="metric-lines"/></article>{[['OCCUPE','Occupés','Occupation déclarée'],['INOCCUPE','Inoccupés','Disponibilité à confirmer'],['INCONNU','État inconnu','Information à compléter']].map(([key,label,sub])=><article className="metric" key={key}><span><i className={`dot ${key}`}/>{label}</span><strong>{String(stats[key]||0).padStart(2,'0')}</strong><small>{sub}</small></article>)}</div><div className="distribution"><strong>Autres états</strong>{mappings.slice(2).map(([,key,label])=><button key={key} onClick={()=>setState(state===key?'':key)} className={state===key?'chosen':''}><Badge state={key} label={label}/><b>{stats[key]||0}</b></button>)}</div></>}
 {(tab==='dashboard'||tab==='csv')&&<section className="panel"><div className="panel-heading"><div><h2>{tab==='dashboard'?'Les lits de votre unité':'Sélection à exporter'} <span className="count">{visible.length}</span></h2><p>{tab==='dashboard'?'Les états sont ceux renseignés sur le serveur.':'L’aperçu et le fichier utilisent exactement les mêmes filtres.'}</p></div>{tab==='dashboard'&&<button className="button secondary" onClick={()=>setTab('csv')}><Download size={15}/>Exporter</button>}</div><div className="filters"><div className="search"><Search size={17}/><input aria-label="Rechercher un lit" placeholder="Rechercher un lit ou un identifiant…" value={query} onChange={e=>setQuery(e.target.value)}/></div><select aria-label="Filtrer par état" value={state} onChange={e=>setState(e.target.value)}><option value="">Tous les états</option>{mappings.map(([,key,label])=><option value={key} key={key}>{label}</option>)}<option value="INCONNU">Inconnu</option></select>{(query||state)&&<button className="text-button" onClick={()=>{setQuery('');setState('');}}>Réinitialiser</button>}</div>{tab==='dashboard'&&<div className="table-scroll"><table><thead><tr><th>LIT / IDENTIFIANT</th><th>ÉTAT OPÉRATIONNEL</th><th>STATUT ADMIN.</th><th>DERNIÈRE MODIFICATION</th><th/></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td><div className="bed-cell"><span className="bed-icon"><BedDouble size={19}/></span><div><strong>{r.name.replace('BEDVIEW · ','').replace(' · FICTIF','')}</strong><small>{r.id}</small></div></div></td><td><Badge state={r.state} label={r.label}/></td><td><span className="admin">{r.admin||'Non renseigné'}</span></td><td className="muted">{date(r.updated)}</td><td><button aria-label={`Voir le JSON du lit ${r.id}`} className="row-action" onClick={()=>{setSelected(r.id);setTab('fhir');}}><ArrowUpRight size={18}/></button></td></tr>)}</tbody></table>{!visible.length&&<div className="empty"><BedDouble size={32}/><h3>{loading?'Lecture des lits…':'Aucun lit à afficher'}</h3><p>{query||state?'Essayez un autre filtre.':'Vérifiez le périmètre ou préparez le jeu avec npm run seed.'}</p></div>}</div>}{tab==='csv'&&<div className="csv-body"><div className="export-summary"><div><strong>{visible.length} ligne(s) de données</strong><p>CSV · UTF-8 · séparateur virgule · contrat 1.0.0</p></div><button className="button primary" disabled={!complete||loading||!!error} onClick={download}><Download size={17}/>Télécharger le CSV</button></div><pre className="code csv-preview">{csv}</pre><p className="help">Les champs contenant des virgules ou guillemets sont échappés. Les textes pouvant être interprétés comme des formules sont protégés. Le CSV omet les champs FHIR non sélectionnés et ne reconstruit pas la ressource complète.</p></div>}<div className="table-footer"><span>{visible.length} lit(s) affiché(s) · {rows.length} dans le périmètre</span><span>{excluded} exclusion(s) · {rows.filter(r=>r.warnings.length).length} lit(s) avec avertissement</span></div></section>}
 {tab==='fhir'&&<><section className="panel"><div className="panel-heading"><div><h2>Ressource source</h2><p>JSON conservé tel que reçu depuis HAPI.</p></div><select aria-label="Sélectionner une ressource" value={current?.id||''} onChange={e=>setSelected(e.target.value)}>{rows.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></div>{current?<><div className="resource-meta"><a href={`${BASE}/Location/${current.id}`} target="_blank" rel="noreferrer">Location/{current.id} <ArrowUpRight size={14}/></a><span>Version {current.raw.meta?.versionId||'non précisée'}</span><button className="text-button" onClick={async()=>{try{await navigator.clipboard.writeText(JSON.stringify(current.raw,null,2));setCopied(true);setTimeout(()=>setCopied(false),1500);}catch{setCopied(false);}}}>{copied?'Copié':'Copier le JSON'}</button></div>{current.warnings.length>0&&<div className="notice">{current.warnings.join(' · ')}</div>}<pre className="code">{JSON.stringify(current.raw,null,2)}</pre></>:<div className="empty">Aucune ressource chargée.</div>}</section><section className="panel journal"><div className="panel-heading"><div><h2>Journal des échanges <span className="count">{logs.length}</span></h2><p>100 derniers appels de cette session.</p></div></div><div className="table-scroll"><table><thead><tr><th>HEURE</th><th>REQUÊTE</th><th>HTTP</th><th>DURÉE</th></tr></thead><tbody>{logs.map((l,i)=><tr key={i}><td>{new Date(l.time).toLocaleTimeString('fr-FR')}</td><td className="log-url"><strong>{l.method} {l.url}</strong>{l.error&&<small>{l.error}</small>}</td><td>{l.status}</td><td>{l.duration} ms</td></tr>)}</tbody></table></div></section></>}
 {tab==='mapping'&&<><section className="panel"><div className="panel-heading"><div><h2>Un vocabulaire partagé</h2><p>Correspondances équivalentes · version 1.0.0</p></div><span className="demo-pill"><Check size={14}/>ConceptMap R4</span></div><div className="mapping-systems"><div><small>SYSTÈME SOURCE</small><code>{SOURCE}</code><span>Référence 2.2.0</span></div><ArrowLeftRight size={24}/><div><small>SYSTÈME CIBLE</small><code>{TARGET}</code><span>Vocabulaire local 1.0.0</span></div></div><div className="table-scroll"><table><thead><tr><th>CODE SOURCE</th><th>SIGNIFICATION</th><th>CODE LOCAL</th><th>LIBELLÉ</th></tr></thead><tbody>{mappings.map(([code,key,label,english])=><tr key={code}><td><code className="code-pill">{code}</code></td><td>{english}</td><td><code>{key}</code></td><td><Badge state={key} label={label}/></td></tr>)}</tbody></table></div><div className="notice">Un code absent, non reconnu ou issu d’un autre système reste INCONNU. Une version source explicite autre que 2.2.0 n’est pas transformée. Une version absente est signalée.</div><details><summary>Consulter le ConceptMap utilisé</summary><pre className="code">{JSON.stringify(conceptMap,null,2)}</pre></details></section><section className="panel journal"><div className="panel-heading"><h2>Transformations appliquées</h2></div><div className="table-scroll"><table><thead><tr><th>LIT</th><th>SOURCE</th><th>CIBLE</th><th>RÉSULTAT / AVERTISSEMENT</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.raw.operationalStatus?.code||'Absent'}</td><td>{r.state}</td><td>{r.result}<small className="warning-text">{r.warnings.join(' · ')}</small></td></tr>)}</tbody></table></div></section></>}
 <div className="bottom-note"><AlertCircle size={16}/><span>Inoccupé ne signifie pas disponible. Les états affichés ne permettent pas à eux seuls de décider d’une admission.</span></div><footer><span>BedView <span className="footer-dot">/</span> Prototype pédagogique</span><span>FHIR R4 · Données fictives · Lecture seule</span></footer></main></div></div>;
}
createRoot(document.getElementById('root')).render(<App/>);
